Repository swift-server/swift-aws-lambda-runtime, pull requests merged in 2022-04, with the labels that each got.

#251 terminator handler
  Sources/AWSLambdaRuntimeCore/LambdaContext.swift
  Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
  Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
  Sources/AWSLambdaRuntimeCore/Terminator.swift
  Sources/AWSLambdaTesting/Lambda+Testing.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeTest.swift
  Tests/AWSLambdaRuntimeCoreTests/Utils.swift
  Tests/AWSLambdaRuntimeTests/Lambda+CodableTest.swift
Labels: ⚠️ needs-major-version-bump

#252 adoption of sendable
  Sources/AWSLambdaRuntimeCore/LambdaContext.swift
  Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
  Sources/AWSLambdaRuntimeCore/Sendable.swift
  Sources/AWSLambdaRuntimeCore/Terminator.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
Labels: 🔼 needs-minor-version-bump

#257 remove extension for JSONEncoder and JSONDecoder
  Sources/AWSLambdaRuntime/Lambda+Codable.swift
Labels: ⚠️ needs-major-version-bump

#256 prefix data structures with Lambda instead of namespacing them
  Examples/Benchmark/BenchmarkHandler.swift
  Examples/Deployment/Sources/Benchmark/BenchmarkHandler.swift
  Examples/Deployment/Sources/HelloWorld/HelloWorldHandler.swift
  Examples/Echo/Lambda.swift
  Examples/ErrorHandling/Lambda.swift
  Examples/Foundation/Lambda.swift
  Examples/JSON/Lambda.swift
  Examples/LocalDebugging/MyLambda/Lambda.swift
  Examples/Testing/Sources/Lambda.swift
  Sources/AWSLambdaRuntimeCore/ControlPlaneRequest.swift
  Sources/AWSLambdaRuntimeCore/HTTPClient.swift
  Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
  Sources/AWSLambdaRuntimeCore/Lambda.swift
  Sources/AWSLambdaRuntimeCore/LambdaConfiguration.swift
  Sources/AWSLambdaRuntimeCore/LambdaContext.swift
  Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
  Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
  Sources/AWSLambdaTesting/Lambda+Testing.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaHandlers.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeTest.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
  Tests/AWSLambdaRuntimeCoreTests/Utils.swift
  Tests/AWSLambdaRuntimeTests/Lambda+CodableTest.swift
  Tests/AWSLambdaTestingTests/Tests.swift
Labels: ⚠️ needs-major-version-bump

#258 Add script to check for API breaks
  scripts/check_no_api_breakages.sh
Labels: enhancement

#262 Drop Swift 5.2 and 5.3
  .swiftformat
  Package.swift
  docker/Dockerfile
  docker/Dockerfile.ubuntu
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.al2.52.yaml
  docker/docker-compose.al2.53.yaml
  readme.md
Labels: 🔼 needs-minor-version-bump

#260 Some documentation fixes
  Sources/AWSLambdaRuntimeCore/LambdaContext.swift
  Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeTest.swift
Labels: ⚠️ needs-major-version-bump
