Repository swift-server/swift-aws-lambda-runtime, pull requests merged in 2025-03, with the labels that each got.

#489 [TestServer] Fix 488 and add simple test lambda
  Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
Labels: 🔨 semver/patch

#493 declare user agent string only once
  Sources/AWSLambdaRuntime/ControlPlaneRequestEncoder.swift
  Sources/AWSLambdaRuntime/LambdaRuntimeClient.swift
  Tests/AWSLambdaRuntimeCoreTests/ControlPlaneRequestEncoderTests.swift
Labels: kind/enhancement, 🔨 semver/patch

#495 remove mentions of LambdaRuntImeCore
  Examples/HelloWorld/README.md
  Examples/Testing/README.md
  Examples/Testing/Tests/HandlerTests.swift
  Package.swift
  Package@swift-6.0.swift
  Sources/AWSLambdaRuntime/Docs.docc/Proposals/0001-v2-api.md
  Tests/AWSLambdaRuntimeTests/ControlPlaneRequestEncoderTests.swift
  Tests/AWSLambdaRuntimeTests/InvocationTests.swift
  Tests/AWSLambdaRuntimeTests/LambdaMockClient.swift
  Tests/AWSLambdaRuntimeTests/LambdaRequestIDTests.swift
  Tests/AWSLambdaRuntimeTests/LambdaRunLoopTests.swift
  Tests/AWSLambdaRuntimeTests/LambdaRuntimeClientTests.swift
  Tests/AWSLambdaRuntimeTests/MockLambdaServer.swift
  Tests/AWSLambdaRuntimeTests/Utils.swift
  Tests/AWSLambdaRuntimeTests/UtilsTest.swift
Labels: 🔨 semver/patch

#496 Fix CI error on Amazon S3 examples
  .github/workflows/integration_tests.yml
  .github/workflows/scripts/integration_tests.sh
Labels: kind/bug, 🔨 semver/patch, area/testing

#497 Attach requestID to logger
  Sources/AWSLambdaRuntime/Lambda.swift
  Tests/AWSLambdaRuntimeTests/CollectEverythingLogHandler.swift
  Tests/AWSLambdaRuntimeTests/LambdaMockClient.swift
  Tests/AWSLambdaRuntimeTests/LambdaRunLoopTests.swift
Labels: 🔨 semver/patch

#499 Remove unnecessary handler constraints
  Sources/AWSLambdaRuntime/Lambda+Codable.swift
  Sources/AWSLambdaRuntime/LambdaHandlers.swift
Labels: ⚠️ semver/major

#503 [example] Update cdk dependencies
  Examples/CDK/infra/package-lock.json
  Examples/CDK/infra/package.json
Labels: area/documentation, semver/none

#506 [plugin] Fix #505 : resources are not included in the archive on Linux
  .github/workflows/scripts/check-archive-plugin.sh
  Plugins/AWSLambdaPackager/Plugin.swift
Labels: 🔨 semver/patch

#510 [ci] : Remove deprecated options on unit-test action
  .github/workflows/pull_request.yml
Labels: semver/none

#511 Add inlinable where potentially usefull
  Sources/AWSLambdaRuntime/ControlPlaneRequest.swift
  Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
  Sources/AWSLambdaRuntime/Lambda.swift
  Sources/AWSLambdaRuntime/LambdaContext.swift
  Sources/AWSLambdaRuntime/LambdaRuntime.swift
  Sources/AWSLambdaRuntime/LambdaRuntimeClient.swift
  Sources/AWSLambdaRuntime/LambdaRuntimeClientProtocol.swift
  Sources/AWSLambdaRuntime/LambdaRuntimeError.swift
  Sources/AWSLambdaRuntime/Utils.swift
Labels: 🆕 semver/minor
