Repository swift-server/swift-aws-lambda-runtime, pull requests merged in 2025-06, with the labels that each got.

#504 [core] Fix LocalServer failure to handle large body request (Issue #481)
  Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
Labels: kind/bug, 🔨 semver/patch

#516 Remove dependency on XCTest
  .gitignore
  Tests/AWSLambdaRuntimeTests/ControlPlaneRequestEncoderTests.swift
  Tests/AWSLambdaRuntimeTests/LambdaRuntimeClientTests.swift
  Tests/AWSLambdaRuntimeTests/MockLambdaServer.swift
  Tests/AWSLambdaRuntimeTests/UtilsTest.swift
  scripts/check-format-linux.sh
  scripts/check-format.sh
Labels: semver/none

#500 [test] add a unit test for the LambdaHTTPServer Pool
  .github/workflows/pull_request.yml
  Package@swift-6.0.swift
  Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
  Tests/AWSLambdaRuntimeTests/PoolTests.swift
Labels: 🔨 semver/patch

#519 Add support for local server graceful shutdown
  Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
  Sources/AWSLambdaRuntime/LambdaRuntime+ServiceLifecycle.swift
  Sources/AWSLambdaRuntime/LambdaRuntime.swift
  Tests/AWSLambdaRuntimeTests/LambdaRuntimeClientTests.swift
Labels: 🔨 semver/patch
