Repository swift-server/swift-aws-lambda-runtime, pull requests merged in 2025-02, with the labels that each got.

#477 Add `S3EventNotifier` example
  .github/workflows/pull_request.yml
  Examples/README.md
  Examples/S3EventNotifier/.gitignore
  Examples/S3EventNotifier/Package.swift
  Examples/S3EventNotifier/README.md
  Examples/S3EventNotifier/Sources/main.swift
Labels: area/documentation, good first issue, semver/none, kind/usability, size/S

#478 Quick typo fix.
  readme.md
Labels: semver/none

#482 Enable Swift 6 mode!
  Package.swift
  Sources/AWSLambdaRuntime/Lambda+Codable.swift
  Sources/AWSLambdaRuntimeCore/Lambda+Codable.swift
  Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
  Sources/AWSLambdaRuntimeCore/LambdaHandlers.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
Labels: ⚠️ semver/major

#483 Using swift-nio 2.81.0
  Package.swift
Labels: 🆕 semver/minor

#459 [core] Add cancellation handling for nextInvocation()
  Sources/AWSLambdaRuntimeCore/Lambda.swift
  Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
  Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTests.swift
Labels: semver/none
