Repository swift-server/swift-aws-lambda-runtime, pull requests merged in 2025-08, with the labels that each got.

#543 Fix link (Response Streaming) in readme.md
  readme.md
Labels: semver/none

#544 Add hummingbird Lambda example
  .github/workflows/pull_request.yml
  Examples/HummingbirdLambda/.gitignore
  Examples/HummingbirdLambda/Package.swift
  Examples/HummingbirdLambda/README.md
  Examples/HummingbirdLambda/Sources/main.swift
  Examples/HummingbirdLambda/template.yaml
  Examples/README.md
Labels: 🆕 semver/minor

#549 Revert streaming codable handler and provide it as an example, not an API
  .github/workflows/pull_request.yml
  Examples/README.md
  Examples/Streaming+Codable/Package.swift
  Examples/Streaming+Codable/README.md
  Examples/Streaming+Codable/Sources/LambdaStreaming+Codable.swift
  Examples/Streaming+Codable/Sources/main.swift
  Examples/Streaming+Codable/Tests/LambdaStreamingCodableTests.swift
  Examples/Streaming+Codable/events/sample-request.json
  Examples/Streaming+Codable/template.yaml
  Sources/AWSLambdaRuntime/FoundationSupport/Vendored/FunctionURL-HTTPType.swift
Labels: ⚠️ semver/major
